[package]
name = "crypto-events"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros"] }

[dev-dependencies]
serde_json = "1"
